<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404180346 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, keywords JSON NOT NULL, context_prompt TEXT DEFAULT NULL, urgency VARCHAR(20) NOT NULL, severity_threshold SMALLINT NOT NULL, cooldown_minutes SMALLINT NOT NULL, categories JSON NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C9687E48A76ED395 ON alert_rule (user_id)');
        $this->addSql('CREATE TABLE notification_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, match_type VARCHAR(50) NOT NULL, transport VARCHAR(100) DEFAULT NULL, success BOOLEAN NOT NULL, ai_severity SMALLINT DEFAULT NULL, ai_explanation TEXT DEFAULT NULL, ai_model_used VARCHAR(100) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, alert_rule_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED15DF2EA1DA493 ON notification_log (alert_rule_id)');
        $this->addSql('CREATE INDEX IDX_ED15DF27294869C ON notification_log (article_id)');
        $this->addSql('CREATE INDEX idx_notification_log_rule_sent ON notification_log (alert_rule_id, sent_at)');
        $this->addSql('ALTER TABLE alert_rule ADD CONSTRAINT FK_C9687E48A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF2EA1DA493 FOREIGN KEY (alert_rule_id) REFERENCES alert_rule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF27294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert_rule DROP CONSTRAINT FK_C9687E48A76ED395');
        $this->addSql('ALTER TABLE notification_log DROP CONSTRAINT FK_ED15DF2EA1DA493');
        $this->addSql('ALTER TABLE notification_log DROP CONSTRAINT FK_ED15DF27294869C');
        $this->addSql('DROP TABLE alert_rule');
        $this->addSql('DROP TABLE notification_log');
    }
}
